publishDir = "docs"

baseURL = "https://agalitsyn.github.io/resume/"

# To check prod build uncomment:
# baseURL = "http://localhost:8080/"

title = "Anton Galitsyn CV"
languageCode = "en-us"

theme = "hugo-orbit-theme"

googleAnalytics = "UA-41903000-5"

disableRSS = true
disableSitemap = true
disable404 = true

[params]
# Meta
    description = "Anton Galitsyn CV"
    author = "Anton Galitsyn"

# Theme styles
    styles = "styles-6.css"

# Sidebar sections
    # Profile section
    [params.profile]
        name = "Anton Galitsyn"
        tagline = "Software Developer"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:anton.galitsyn@gmail.com"
        title = "anton.galitsyn"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+79133867287"
        # title = "+79133867287"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//agalitsyn.github.io"
        title = "agalitsyn.github.io"

        [[params.contact.list]]
        class = "telegram"
        icon = "fa-paper-plane"
        url = "//t.me/agalitsyn"
        title = "agalitsyn"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/anton-galitsyn-a31925179"
        title = "anton-galitsyn"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/agalitsyn"
        title = "github.com/agalitsyn"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/anton_galitsyn"
        title = "@anton_galitsyn"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Engineer"
        college = "Siberian State University of Telecommunications and Information Sciences"
        dates = "2006 - 2011"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Russian"
        level = "Native"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = ""

# Main body sections
    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """Last 5 years my fulltime job was related to Go programming,
both on product side (developing various services) and techinical side (tools and libraries).
I perform tasks of diverse level of complexity, which require detailed analysis, selection of solutions, in other words
I can transform amorphous requirements from business into a working system. Often I act as a techlead for some feature.
Also I often addressed for help by others, sometimes acts as a mentor.

Personally I'm passionate about creating software products, which can improve every-day life of customers or developers.
I always tend to be a diligent person, concentrate upon an objectives and work out it properly.
It’s important for me to have self-possession and to be laid-back and modest person for team-members.
        """

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior software developer"
        dates = "2021 - Present"
        company = "AliExpress Russia"
        product = "Seller center"
        product_url = "//seller.aliexpress.ru"
        stack = "Go, gRPC, k8s, kafka, postgres, redis, s3"
        details = """Seller Center is a space where sellers can manage their products, logistics, stats, etc.
Generally, all tasks is about building various HTTP + gRPC backends in k8s environment, some of them includes:
* Using gRPC-Gateway
* Consumer, Producer for Apache Kafka
* RBD storage - postgres. Bulk inserts, updates, query optimization, applying indexes, etc.
* Caching in memory or in Redis
* Storing data in S3
* Distributes locks with etcd

Personally I like to use one-repository approach for services with multiple apps inside, demo you can find here https://github.com/agalitsyn/go-app and check out readme.
        """

        [[params.jobs.list]]
        position = "Senior software developer"
        dates = "2018 - end 2020"
        company = "Positive Technologies"
        product = "Cybersecurity Intelligence"
        product_url = "//ptsecurity.com/ru-ru/products/cybersecurity-intelligence"
        stack = "Go, docker, ansible, gitlab-ci, python"
        details = """This product is about:
* Analytics system for security reports with data enrichment and search.
* Aggregations, indicator correlations, output feeds.
* Generic API for 3rd-party software.
* Integration with security software of other vendors like Trendmicro, VirusTotal, etc.

I did achitecture and development of several subsystems: Auth, API, artifact analyzer gateway, storage system, data migrations.
Also I did CI and deployment a lot, before infrastructure engineers was hired.
        """

        [[params.jobs.list]]
        position = "Senior software developer"
        dates = "2017 - 2018"
        company = "Tinkoff"
        product = "Investment"
        product_url = "//tinkoff.ru/invest"
        stack = "Go, kafka, postgres, docker, rancher, teamcity"
        details = """Senior engineer of Market-data service for invest platform.
This service uses streaming architecture, one part of it should fetch
data from different exchanges, parse it and send to Kafka, then aggregators depuplicate messages and
and store in unified format in storage, then all data is accessible using REST API.
Also I did CI/CD, deploy, monitoring, logging parts.
        """

        [[params.jobs.list]]
        position = "Senior software developer"
        dates = "2016 - 2017"
        company = "Gravitational"
        product = "Gravity"
        product_url = "//goteleport.com/gravity"
        stack = "Go, kubernetes, terraform, prometheus, grafana, jenkins"
        details = """Worked on several applications, which runs on
[gravitational/gravity](https://github.com/gravitational/gravity) platform.
Basically all apps was Go apps, which uses k8s resoures and APIs.

Also I worked with:
* [sorintlab/stolon](https://github.com/sorintlab/stolon)
* [helm/helm](https://github.com/helm/helm/pull/1766).
        """

        [[params.jobs.list]]
        position = "Software developer"
        dates = "2014 - 2016"
        company = "2GIS"
        product = "Infrastructure and operations"
        product_url = "//2gis.ru"
        stack = "python, ansible, gitlab-ci and last year Go"
        details = """At first year I worked on integration of [openstack](http://openstack.org)
as a private cloud solution for whole company.
I maintained several custom plugins and "ready to go" templates for openstack orchestration
([heat](https://github.com/openstack/heat)),
also I actively worked on compute ([nova](https://github.com/openstack/nova)),
DNS ([designate](https://github.com/openstack/designate))
and openstack deployment ([openstack-ansible](https://github.com/openstack/openstack-ansible)).
Also I did tech support for developers, consulting on how to use openstack.
Last year I was involved into researches on container infrastructure, I worked with docker, CoreOS, deis, etc.
        """

        [[params.jobs.list]]
        position = "Software developer"
        dates = "2014 - 2014"
        company = "Parallels"
        product = "Shared hosting automation"
        product_url = "//odin.com/ru/products/premium"
        stack = "LAMP, python, bash"
        details = """This is 10 y.o. project with SOA architecture, old core was in C++, new in Java, cores
communicates using CORBA.
I worked on extension - dispatcher component: service written in PHP (Symfony 2 and Doctrine)
with multiple integration points: REST, CLI, RPC. Main goal was infrastructure management, upgrade and
health monitoring.
So, some part of my tasks still has some PHP for REST APIs, but second part was development for linux
using bash and python.
        """

        [[params.jobs.list]]
        position = "Junior software developer"
        dates = "2013 - 2014"
        company = "Parallels"
        product = "Web Presence Builder"
        product_url = "//odin.com/cz/products/web-presence-builder"
        stack = "LAMP on backend, JS on frontend"
        details = """I worked on interactive website builder. Project was created in 2004 and consists of legacy codebase
with layered architecture. Generally it was SPA web app which communicates with backend using REST API.
I participated in release WPB 11.6, and then next 8 month worked on WPB 12,
which was never released, because project was closed by management.
        """

        [[params.jobs.list]]
        position = "Web developer"
        dates = "2011 - 2013"
        company = "i20"
        product = ""
        product_url = "//drupaljedi.com"
        stack = "Drupal, PHP, JS, JQuery"
        details = """I was involved in building webistes as a fullstack developer.
Released several TV-channels websites, restaurants,
cultural & educational media website, corporate website.
        """

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Go"

        [[params.skills.list]]
        skill = "Test automation"

        [[params.skills.list]]
        skill = "Monitoring and alerting"

        [[params.skills.list]]
        skill = "CI/CD pipelines"

        [[params.skills.list]]
        skill = "Linux system administration"

        [[params.skills.list]]
        skill = "Configuration management systems, deployment orchestration tools, containers"

        [[params.skills.list]]
        skill = "Management of release process for small teams"

        [[params.skills.list]]
        skill = "Training software engineers"

        [[params.skills.list]]
        skill = "Basic HTML & CSS, JS frameworks, bulding internal UIs"

    # Footer section
    [params.footer]
        copyright = "Anton Galitsyn"
